language: rust
cache: cargo

rust:
- stable

install:
- rustup component add rustfmt --toolchain stable
- rustup component add clippy --toolchain stable
- curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 

script:
 - ./ci/cargo_check.sh 
 - make