language: rust
cache: cargo

rust:
# - stable
  - nightly

before_install:
- set -e
- rustup self update

install:
#- rustup toolchain install nightly-2019-06-22
- rustup component add rustfmt-preview
- rustup component add clippy-preview
- cargo install -f wasm-pack  

before_script:
- chmod +x ./ci/script.sh
script:
 - ./ci/script.sh 
 - make -C ci 