language: rust
cache: cargo

rust:
# - stable
  - nightly

before_install:
- set -e
- rustup self update

install:
# - rustup toolchain install nightly-2019-06-22
# - rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
- rustup component add rustfmt
# - rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
- rustup component add clippy
- cargo install wasm-pack || echo "wasm-pack already installed"
before_script:
- chmod +x ./ci/script.sh
script:
 - ./ci/script.sh 
 - make -C ci 