language: rust
cache: cargo

rust:
- stable

install:
- rustup component add rustfmt --toolchain stable
- rustup component add clippy --toolchain stable
- curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 

before_script:
   - chmod +x ./ci/cargo_check.sh
script:
 - ./ci/cargo_check.sh 
 - make