language: rust
cache: cargo
  # directories:
  # - "demo/node_modules"

rust:
 - nightly

before_install:
- rustup self update

install:
 - rustup update nightly-2019-06-22
 - rustup component add --toolchain nightly-2019-06-22 rustfmt
 - rustup component add --toolchain nightly-2019-06-22 clippy
 - cargo install wasm-pack || echo "wasm-pack already installed"

before_script:
- chmod +x ./ci/script.sh

script:
 - ./ci/script.sh 


deploy:
  provider: pages
  skip-cleanup: true
  verbose: true
  local-dir: target
  github_token: $GITHUB_TOKEN
  keep-history: true
  repo: tronch0/webassemblydemo #github.com/QED-it/zkinterface-wasm-demo   # gh-username/gh-username.github.io
  target-branch: master
  on:
    branch: master

