language: rust
cache: cargo

rust:
# - stable
  - nightly

before_install:
- set -e
- rustup self update

install:
- rustup component add rustfmt
- rustup component add clippy
- cargo install -f wasm-pack  

before_script:
   - chmod +x ./ci/cargo_check.sh
script:
 - ./ci/script.sh 
 - make -C ci 