language: rust
cache: cargo

rust:
# - stable
  - nightly

before_install:
- set -e
- rustup self update

install:
- rustup toolchain install nightly-2019-06-22
- cargo install wasm-pack || echo "wasm-pack already installed"
- cargo install-update -a
before_script:
- chmod +x ./ci/script.sh
script:
 - ./ci/script.sh 
 - make -C ci 