language: rust
cache: cargo

rust:
# - stable
  - nightly

install:
- rustup component add rustfmt #--toolchain stable
- rustup component add clippy #--toolchain stable
- cargo install -f wasm-pack  

before_script:
   - chmod +x ./ci/cargo_check.sh
script:
 - ./ci/cargo_check.sh 
 - make